using System;
using System.IO;
using Ionic.Zip;
using System.Threading;
using System.ComponentModel;
using Frends.Zip.ExtractArchive.Definitions;

namespace Frends.Zip.ExtractArchive;

/// <summary>
/// ZIP task.
/// </summary>
public static class Zip
{
    /// <summary>
    /// A Frends task for extracting zip archives.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.Zip.ExtractArchive)
    /// </summary>
    /// <param name="input">Input parameters.</param>
    /// <param name="options">Options parameters.</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this task.</param>
    /// <returns>Object { List&lt;string&gt; ExtractedFiles }</returns>
    public static UnzipOutput ExtractArchive([PropertyTab] UnzipInputProperties input,
        [PropertyTab] UnzipOptions options, CancellationToken cancellationToken)
    {
        if (!File.Exists(input.SourceFile))
            throw new FileNotFoundException($"Source file {input.SourceFile} does not exist.");
        if (!Directory.Exists(input.DestinationDirectory) && !options.CreateDestinationDirectory)
            throw new DirectoryNotFoundException($"Destination directory {input.DestinationDirectory} does not exist.");
        if (options.CreateDestinationDirectory) Directory.CreateDirectory(input.DestinationDirectory);

        var output = new UnzipOutput();

        using (var zip = ZipFile.Read(input.SourceFile))
        {

            if (!string.IsNullOrWhiteSpace(input.Password)) zip.Password = input.Password;

            foreach (var z in zip)
            {
                cancellationToken.ThrowIfCancellationRequested();

                if (z.Attributes.HasFlag(FileAttributes.Directory)) continue;

                string normalizedEntryPath = z.FileName
                    .Replace('/', Path.DirectorySeparatorChar)
                    .Replace('\\', Path.DirectorySeparatorChar);

                var targetFilePath = Path.GetFullPath(Path.Combine(input.DestinationDirectory, normalizedEntryPath));

                if (File.Exists(targetFilePath))
                {
                    if (options.DestinationFileExistsAction == UnzipFileExistAction.Error)
                    {
                        throw new IOException($"Destination file already exists: {targetFilePath}");
                    }

                    if (options.DestinationFileExistsAction == UnzipFileExistAction.Rename)
                    {
                        targetFilePath = Extensions.GetNewFilename(
                            Path.Combine(input.DestinationDirectory, normalizedEntryPath),
                            cancellationToken);
                    }
                }

                string directory = Path.GetDirectoryName(targetFilePath);
                if (directory != null) Directory.CreateDirectory(directory);

                using var fs = File.Create(targetFilePath);
                z.Extract(fs);
                output.ExtractedFiles.Add(targetFilePath);
            }
        }


        if (!options.DeleteZipFileAfterExtract) return output;
        try
        {
            File.Delete(input.SourceFile);
        }
        catch (Exception ex)
        {
            throw new ArgumentException(
                $"Extraction was completed but an exception was thrown when trying to delete the source file: {ex.Message}");
        }

        return output;
    }
}
