name: build_and_test_on_push.yml

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.Zip.CreateArchive/**'
  workflow_dispatch:
    paths:
      - 'Frends.Zip.CreateArchive/**'
  
defaults:
  run:
    working-directory: './Frends.Zip.CreateArchive'

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      