name: CreateArchive_push

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.Zip.CreateArchive/**'
  workflow_dispatch:
    paths:
      - 'Frends.Zip.CreateArchive/**'

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@ISSUE-9
    with:
      workdir: Frends.Zip.CreateArchive
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      