name: CreateArchive_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.Zip.CreateArchive/**'
  workflow_dispatch:
    paths:
      - 'Frends.Zip.CreateArchive/**'

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.Zip.CreateArchive
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}