name: release.yml

on:
  workflow_dispatch:
    paths:
      - 'Frends.Zip.CreateArchive/**'

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/release.yml@main
    secrets:
      feed_api_key: ${{ secrets.TASKS_FEED_API_KEY }}
      