name: ExtractArchive_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.Zip.ExtractArchive/**'
  workflow_dispatch:
    paths:
      - 'Frends.Zip.ExtractArchive/**'

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.Zip.ExtractArchive
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      